server.port: 0

grpc:
  server:
    port: 0

collector:
  kafka:
    producer:
      user-action-topic: "stats.user-actions.v1"

spring:
  kafka:
    producer:
      bootstrap-servers: "localhost:9092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.stats.serialization.avroschemas.AvroSerializer
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org.springframework.cloud.loadbalancer: WARN
    com.netflix.discovery: WARN
    collector: DEBUG
