server:
  port: 0

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/main
    username: main
    password: main
  sql:
    init:
      mode: never
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.time_zone: UTC

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
    springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    request.service.controller: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    event.service: DEBUG